version: '3.8'

services:
  nestapp:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgresdb
    env_file: .env.development

  postgresdb:
    image: postgres
    restart: always
    env_file: .env.development
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
