// Generated by https://quicktype.io

export interface ICart {
  description: string;
discount: number;
idSubProduct: string;
idProduct: string;
imgUrl: string;
price:number;
quantity: number;
size: number;
stock:number;
unit: string;

}

export interface IProductList {
  id: string;
  description: string;
  imgUrl: string;
  averageRating: string;
  isDeleted: boolean;
  category: Category;
  quantity?: number;
  subproducts: ISubProduct[];
}
export interface ISubProduct {
presentacion?: string;
tipoGrano?: string;
amount: string
id: number
price: string
stock: number
unit: string
isAvailable: boolean
discount: number;
}

export interface Category {
  id: string;
  name: string;
}

export interface IProductResponse {
  article_id: string;
  description: string;
  imgUrl: string;
  price: string;
  stock: string;
  discount: string;
  presentacion?: string;
  tipoGrano?: string;
  medida?: string;
  categoryID: string;
}

export interface IProductErrorResponse {
  article_id: string;
  description: string;
  imgUrl: string;
  price: string;
  stock: string;
  discount: string;
  presentacion?: string;
  tipoGrano?: string;
  medida?: string;
  categoryID: string;
}

export interface IProductUpdate {
  description: string;
  price: string;
  stock: string;
  discount: string;
  presentacion: string;
  tipoGrano: string;
  medida: string;
  categoryID: string;
  file?: File;
}

export interface IProductErrorUpdate {
  description: string;
  price: string;
  stock: string;
  discount: string;
  presentacion: string;
  tipoGrano: string;
  medida: string;
  categoryID: string;
}
