// Generated by https://quicktype.io

export interface IProductList {
  size?:number;
  id: string;
  article_id: string;
  description: string;
  imgUrl: string;
  price: string;
  stock: string;
  discount: string;
  averageRating: string;
  isAvailable: boolean;
  isDeleted: boolean;
  category: Category;
  presentacion?: string;
  tipoGrano?: string;
  quantity?: number;
  medida?: string;
  subproducts?: ISubProduct[];

}
export interface ISubProduct {
amount: string
id: number
price: string
stock: number
unit: string
isAvailable: boolean
}

export interface Category {
  id: string;
  name: string;
}

export interface IProductResponse {
  description: string;
  categoryID: string;
  presentacion: string;
  tipoGrano: string;
  file?: File;
  amount?: string;
  unit?: string;
  stock?: string;
  price?: string;
  discount?: string;
}

export interface IProductErrorResponse {
  description: string;
  categoryID: string;
  presentacion: string;
  tipoGrano: string;
  file?: string;
  amount?: string;
  unit?: string;
  stock?: string;
  price?: string;
  discount?: string;
}

export interface IProductUpdate {
  description: string;
  categoryID: string;
  presentacion: string;
  tipoGrano: string;
  file?: File;
  amount?: string;
  unit?: string;
  stock?: string;
  price?: string;
  discount?: string;
}

export interface IProductErrorUpdate {
  description: string;
  categoryID: string;
  presentacion: string;
  tipoGrano: string;
  file?: string;
  amount?: string;
  unit?: string;
  stock?: string;
  price?: string;
  discount?: string;
}
