const provinciasHelper = {
    "Buenos Aires": [
      "25 de Mayo",
      "9 de Julio",
      "Adolfo Alsina",
      "Adolfo Gonzales Chaves",
      "Alberti",
      "Almirante Brown",
      "Arrecifes",
      "Avellaneda",
      "Ayacucho",
      "Azul",
      "Bahía Blanca",
      "Balcarce",
      "Baradero",
      "Benito Juárez",
      "Berazategui",
      "Berisso",
      "Bolívar",
      "Bragado",
      "Brandsen",
      "Campana",
      "Cañuelas",
      "Capitán Sarmiento",
      "Carlos Casares",
      "Carlos Tejedor",
      "Carmen de Areco",
      "Castelli",
      "Chacabuco",
      "Chascomús",
      "Chivilcoy",
      "Colón",
      "Coronel Dorrego",
      "Coronel Pringles",
      "Coronel Rosales",
      "Coronel Suárez",
      "Daireaux",
      "Dolores",
      "Ensenada",
      "Escobar",
      "Esteban Echeverría",
      "Exaltación de la Cruz",
      "Ezeiza",
      "Florencio Varela",
      "Florentino Ameghino",
      "General Alvarado",
      "General Alvear",
      "General Arenales",
      "General Belgrano",
      "General Guido",
      "General Juan Madariaga",
      "General La Madrid",
      "General Las Heras",
      "General Lavalle",
      "General Paz",
      "General Pinto",
      "General Pueyrredón",
      "General Rodríguez",
      "General San Martín",
      "General Viamonte",
      "General Villegas",
      "Guaminí",
      "Hipólito Yrigoyen",
      "Hurlingham",
      "Ituzaingó",
      "José C. Paz",
      "Junín",
      "La Costa",
      "La Matanza",
      "La Plata",
      "Lanús",
      "Laprida",
      "Las Flores",
      "Leandro N. Alem",
      "Lezama",
      "Lincoln",
      "Lobería",
      "Lobos",
      "Lomas de Zamora",
      "Luján",
      "Magdalena",
      "Maipú",
      "Malvinas Argentinas",
      "Mar Chiquita",
      "Marcos Paz",
      "Mercedes",
      "Merlo",
      "Monte",
      "Monte Hermoso",
      "Moreno",
      "Morón",
      "Navarro",
      "Necochea",
      "Patagones",
      "Pehuajó",
      "Pellegrini",
      "Pergamino",
      "Pila",
      "Pilar",
      "Pinamar",
      "Presidente Perón",
      "Puán",
      "Punta Indio",
      "Quilmes",
      "Rauch",
      "Rivadavia",
      "Rojas",
      "Roque Pérez",
      "Saavedra",
      "Saladillo",
      "Salliqueló",
      "Salto",
      "San Andrés de Giles",
      "San Antonio de Areco",
      "San Cayetano",
      "San Fernando",
      "San Isidro",
      "San Miguel",
      "San Nicolás",
      "San Pedro",
      "San Vicente",
      "Suipacha",
      "Tandil",
      "Tapalqué",
      "Tigre",
      "Tordillo",
      "Tornquist",
      "Trenque Lauquen",
      "Tres Arroyos",
      "Tres de Febrero",
      "Tres Lomas",
      "Vicente López",
      "Villarino",
      "Zárate"
    ],
    "Ciudad Autónoma de Buenos Aires": [
      "Agronomía",
      "Almagro",
      "Balvanera",
      "Barracas",
      "Belgrano",
      "Boedo",
      "Caballito",
      "Chacarita",
      "Coghlan",
      "Colegiales",
      "Constitución",
      "Flores",
      "Floresta",
      "La Boca",
      "Liniers",
      "Mataderos",
      "Monte Castro",
      "Monserrat",
      "Nueva Pompeya",
      "Núñez",
      "Palermo",
      "Parque Avellaneda",
      "Parque Chacabuco",
      "Parque Chas",
      "Parque Patricios",
      "Paternal",
      "Puerto Madero",
      "Recoleta",
      "Retiro",
      "Saavedra",
      "San Cristóbal",
      "San Nicolás",
      "San Telmo",
      "Vélez Sársfield",
      "Versalles",
      "Villa Crespo",
      "Villa del Parque",
      "Villa Devoto",
      "Villa General Mitre",
      "Villa Lugano",
      "Villa Luro",
      "Villa Ortúzar",
      "Villa Pueyrredón",
      "Villa Real",
      "Villa Riachuelo",
      "Villa Santa Rita",
      "Villa Soldati",
      "Villa Urquiza"
    ],
    "Córdoba": [
      "Córdoba Capital",
      "Villa María",
      "Río Cuarto",
      "Carlos Paz",
      "San Francisco",
      "Otros"
    ],
    "Santa Fe": [
      "Rosario",
      "Santa Fe Capital",
      "Rafaela",
      "Reconquista",
      "Otros"
    ],
    "Mendoza": [
      "Mendoza Capital",
      "San Rafael",
      "Godoy Cruz",
      "Luján de Cuyo",
      "Otros"
    ],
    "Tucumán": [
      "San Miguel de Tucumán",
      "Tafí Viejo",
      "Otros"
    ],
    "Entre Ríos": [
      "Paraná",
      "Concordia",
      "Otros"
    ],
    "San Juan": [
      "San Juan Capital",
      "Rawson",
      "Rivadavia",
      "Otros"
    ],
    "Salta": [
      "Salta Capital",
      "San Ramón de la Nueva Orán",
      "Otros"
    ],
    "Jujuy": [
      "San Salvador de Jujuy",
      "Palpalá",
      "Otros"
    ],
    "Río Negro": [
      "Viedma",
      "San Carlos de Bariloche",
      "Otros"
    ],
    "Chubut": [
      "Rawson",
      "Comodoro Rivadavia",
      "Otros"
    ],
    "Neuquén": [
      "Neuquén Capital",
      "Cutral-Có",
      "Otros"
    ],
    "San Luis": [
      "San Luis Capital",
      "Villa Mercedes",
      "Otros"
    ],
    "La Rioja": [
      "La Rioja Capital",
      "Chilecito",
      "Otros"
    ],
    "Catamarca": [
      "San Fernando del Valle de Catamarca",
      "Otros"
    ],
    "La Pampa": [
      "Santa Rosa",
      "Otros"
    ],
    "Formosa": [
      "Formosa Capital",
      "Otros"
    ],
    "Chaco": [
      "Resistencia",
      "Sáenz Peña",
      "Otros"
    ],
    "Corrientes": [
      "Corrientes Capital",
      "Goya",
      "Otros"
    ],
    "Misiones": [
      "Posadas",
      "Oberá",
      "Otros"
    ],
    "Santiago del Estero": [
      "Santiago del Estero Capital",
      "Otros"
    ],
    "Santa Cruz": [
      "Río Gallegos",
      "Otros"
    ],
    "Tierra del Fuego": [ 
      "Río Grande",
      "Ushuaia",
      "Otros"
    ]
  };
  
  export default provinciasHelper;